name: make-release
run-name: Make release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make ci_build_64tass
      - run: make VERBOSE=1 "TASSCMD=$(HOME)/tass64-code/64tass"
